# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='avatar',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
