# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quad', '0002_auto_20160730_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='avatar',
            field=models.FileField(null=True, upload_to=b''),
        ),
    ]
