# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quad', '0003_auto_20160730_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.FileField(upload_to='img_blog'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='avatar'),
        ),
    ]
