# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-16 12:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quad', '0006_auto_20160730_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
