# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-17 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quad', '0009_auto_20160817_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quad.Comment'),
        ),
    ]
