# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-26 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quad', '0013_remove_article_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='author',
        ),
        migrations.RemoveField(
            model_name='like',
            name='comment',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
